apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-order-deployment
  labels:
    app: nagp-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nagp-order
  template:
    metadata:
      labels:
        app: nagp-order
    spec: 
      containers:
      - name: nagp-order
        image: jagratigoyal/ass3order:tag2
        env:
         - name: JAEGER_HOST
           valueFrom:
            configMapKeyRef:
             name: app-env-config-url
             key: JAEGER_HOST
        ports:
        - containerPort: 8085